
import { Forfait } from './forfait';

export const forfaits : Forfait [] = [
    {
        destination: 'Cancun, Mexique',
        villeDeDepart: 'Québec',
        hotel: {
            nom: 'Hard Rock Hotel Cancun',
            adresse: ' Boulevard Kukulcan Km 14.5 Hotel Zone, 77500 Cancún, México ',
            photo: "https://cdn.travelpulse.com/images/99999999-9999-9999-9999-999999999999/7411ad9a-bf4b-8f77-1993-6ea9fd4f389c/630x355.jpg",
            etoiles: 5,
            nbChambres: 250,
            caracteristiques: [ 'Face à la plage',
                                '2 piscines',
                                'Vue sur le lac',
                                'Climatisation',
                                "Salle de bains privative dans l'hébergemen", 
                                'Ascenseur',
                                'All inclusive Restaurants',
                                'Miniclub ', 
                                'Salon de mariages'],
        },
        dateDepart: '20/11/2020',
        dateRetour: '27/11/2020',
        prix: 2300,
        forfaitVedette: false,
        rabais: 0
    },
    {
        destination: 'Cancun, Mexique',
        villeDeDepart: 'Québec',
        hotel: {
            nom: 'The Pyramid at Grand Oasis',
            adresse: 'Blvd. Kulculcan Km 16.5, 77500 Cancún, México',
            photo:  "https://oasishoteles.sfo2.cdn.digitaloceanspaces.com/assets/img/hoteles/the-pyramid-at-grand-oasis/header/header-pyr-full.jpg",
            etoiles: 5,
            nbChambres: 650,
            caracteristiques: [ 'Tout inclus',
                                'Face à la plage',
                                'Miniclub ',
                                '6 piscines',
                                '10 restaurants',
                                '7 bars', 
                                'Vue sur le lac',
                                'Spa 24h', 
                                'Salon de mariages'],
        },
        dateDepart: '1/01/2021',
        dateRetour: '08/01/2021',
        prix: 2005,
        forfaitVedette: false,
        rabais: 0
    },
    {
        destination: 'Cancun, Mexique',
        villeDeDepart: 'Québec',
        hotel: {
            nom: 'Paradisus by Meliá Cancún',
            adresse: 'Kukulcan Boulevard Km 16.5, 77500 Cancún, Mexique',
            photo: "https://cf.bstatic.com/images/hotel/max1280x900/142/14213295.jpg",
            etoiles: 5,
            nbChambres: 350,
            caracteristiques: [ 'Tout inclus', 
                                'Face à la plage',
                                '4 piscines',
                                'Vue sur le lac',
                                'Climatisation',
                                "Navette aéroport",
                                "Wi-Fi : Gratuit", 
                                'Terrasse',
                                'Aire de jeux pour enfants', 
                                'Salon de mariages'],
        },
        dateDepart: '24/12/2020',
        dateRetour: '31/12/2020',
        prix: 1799,
        forfaitVedette: false,
        rabais: 0
    },
    {
        destination: 'Punta Cana, Republique Dominicaine',
        villeDeDepart: 'Quebec',
        hotel: {
            nom: 'Majestic Colonial Punta Cana',
            adresse: ' Playa Bavaro Punta Cana, Bávaro, 21220 Punta Cana, República Dominicana',
            photo: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/2b/91/be/aerial-photography--v18293200.jpg?w=900&h=-1&s=1",
            etoiles: 5,
            nbChambres: 300,
            caracteristiques: [ 'Tout inclus', 
                                'Plage privé',
                                'Salle de sport',
                                'Spa et centre de bien-être',
                                'All inclusive restaurants',
                                'Face à la plage',
                                'Aire de jeux pour enfants', 
                                'Salon de mariages'],
        },
        dateDepart: '21/12/2020',
        dateRetour: '31/12/2020',
        prix: 1670,
        forfaitVedette: true,
        rabais: 300
    },
    {
        destination: 'Punta Cana, Republique Dominicaine',
        villeDeDepart: 'Québec',
        hotel: {
            nom: 'Majestic Mirage Punta Cana',
            adresse: 'Playa - Bavaro, Punta Cana, Bávaro, 12345 Punta Cana, República Dominicana',
            photo: "https://wcm.transat.com/getmedia/79e3ae50-4b2b-43bd-ae89-dc7381b8f641/Majestic-Mirage-Aerial-001.aspx",
            etoiles: 4,
            nbChambres: 320,
            caracteristiques: [ 'Tout inclus',
                                'Plage privé',
                                'Salle de sport',
                                'Spa et centre de bien-être',
                                'All inclusive restaurants',
                                '5 restaurants',
                                '5 bars',
                                'garderie le soir',
                                'Face à la plage',
                                'Aire de jeux pour enfants', 
                                'Salon de mariages'],
        },
        dateDepart: '21/12/2020',
        dateRetour: '01/01/2021',
        prix: 1500,
        forfaitVedette: true,
        rabais: 100
    },
    {
        destination: 'Punta Cana, Republique Dominicaine',
        villeDeDepart: 'Québec',
        hotel: {
            nom: 'Catalonia Punta Cana',
            adresse: 'Playas de Bavaro, Cabeza de Toro, 23000 Punta Cana, República Dominicana',
            photo: "https://cf.bstatic.com/images/hotel/max1280x900/151/151788013.jpg",
            etoiles: 5,
            nbChambres: 150,
            caracteristiques: [ 'Face à la plage', 
                                "2 piscines",
                                '1 restaurants all inclusive',
                                'Spa et centre de bien-être',
                                'Miniclub',
                                "Salle d'exercice", 
                                'Salon de mariages'],
        },
        dateDepart: '21/12/2020',
        dateRetour: '01/01/2021',
        prix: 1500,
        forfaitVedette: true,
        rabais: 300
    },
];